nome = input ('Qual é o seu nome? ')
print ('Prazer em te conhecer {:=^20}!'.format(nome))
n1 = int(input ('Um valor: '))
n2 = int(input ('Outro valor: '))
print ('A soma vale {}'.format(n1 + n2))
